### ISSUE TITLE
Evaluation points sales catcher

### ISSUE THREAD

**Issue by drakosa13** [JakeBV/peer_location_bot#1]
Привет. А нельзя добавить функционал о появлении "Evaluation points sales are now starting for a limited time ! Enjoy !"
А то я все время их пропускаю( уже не знаю чего и делать)

Хотя наверное в скоуп "peer_location" может это и не очень ложиться(

**Comment by JakeBV** [comment]
Привет. Не встречал такой метод в апи интры, да и правда в скоуп "peer_location" это не очень ложится. Плюс, вероятно, для разных страны распродажа в разное время (но это не точно), так что каждому юзеру придется как-то указывать свой кампус.
